export {ReactComponent as Video} from '../svg/feather-video.svg'
export {ReactComponent as Phone} from '../svg/feather-phone.svg'
export {ReactComponent as Image} from '../svg/feather-image.svg'
export {ReactComponent as PaperClip} from '../svg/feather-paperclip.svg'
export {ReactComponent as PlusCircle} from '../svg/feather-plus-circle.svg'
export {ReactComponent as Smile} from '../svg/feather-smile.svg'
export {ReactComponent as ChatImg} from '../svg/ChatImg.svg'
export {ReactComponent as ThumbsUp} from '../svg/feather-thumbs-up.svg'
export { ReactComponent as ClockRegular } from '../svg/clock-regular.svg'
export { ReactComponent as InstagramBrands } from '../svg/instagram-brands.svg'
export { ReactComponent as PhoneAlt } from '../svg/phone-alt-solid.svg'
export { ReactComponent as Search } from '../svg/search-solid.svg'
export { ReactComponent as Telegram } from '../svg/telegram-plane.svg'
export { ReactComponent as Vk } from '../svg/Vector.svg'
export { ReactComponent as Whatsapp } from '../svg/whatsapp.svg'
export { ReactComponent as Youtube } from '../svg/youtube.svg'
export { ReactComponent as LessThan } from '../svg/less-than.svg'
export { ReactComponent as Arrow } from '../svg/arrow.svg'
export { ReactComponent as Overview } from '../svg/overview.svg'
export { ReactComponent as Tickets } from '../svg/tickets.svg'
export { ReactComponent as Contacts } from '../svg/contacts.svg'
export { ReactComponent as Agents } from '../svg/agents.svg'
export { ReactComponent as Settings } from '../svg/settings.svg'
export { ReactComponent as Product } from '../svg/product.svg'


